# Use Node base image
FROM node:18

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy all source code
COPY . .

# Install nodemon globally
RUN npm install -g nodemon

# Expose backend port
EXPOSE 5000

# Start with nodemon for dev
CMD ["nodemon", "server.js"]
